### PR TITLE
#5 - fixed copyright section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks, I'll find someone to review it before we merge

**Comment by dmarkov** [comment]
@carlosmiranda please review

**Comment by carlosmiranda** [comment]
@rultor Can we merge now?

**Comment by dmarkov** [comment]
@carlosmiranda thanks, paid, **16 mins** to your account, payment ID is `50570929`. +16 to your rating, your total score is [+1785](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
