### PR TITLE
test method name correction

### PR DESCRIPTION
**Pull request by prondzyn**
Just a test method name correction. Not connected with any issue.

### CODE REVIEW

**Comment by dmarkov** [comment]
@prondzyn Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 I added **16 mins** to your account, many thanks for working with the project! The completion time here was 000-9d579a21.; you're getting extra minutes here (c=1); +16 to your rating, your total score is [+9098](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
