### PR TITLE
DefaultValidationResponse is not immutable

### PR DESCRIPTION
**Pull request by piddubnyi**
Removed unused setter method to make class immutable.
https://github.com/jcabi/jcabi-w3c/issues/25

### CODE REVIEW

**Comment by dmarkov** [comment]
@piddubnyi Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 pull request is rather short, review it please

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 done, I added **16 mins** in payment `000-a9beb123`, 114 hours and 31 mins spent to complete this; you're getting extra minutes here (c=1); +16 added to your rating, at the moment it is: [+7793](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
