### PR TITLE
modified .gitignore with more files

### PR DESCRIPTION
**Pull request by simonjenga**
modified .gitignore with more files

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 the pull request is rather small, pls review it

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 paid, thanks, added **16 mins** to your account, payment `000-8d943bf3`, 3 hours and 1 min was spent. extra minutes for review comments (c=1). +16 added to your rating, current score is: [+8381](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
